# Generated by Django 3.1.2 on 2022-06-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ejercicios_asignar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicios',
            name='asignar',
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='asignar',
            field=models.ManyToManyField(to='app.queQuieres'),
        ),
    ]
