# Generated by Django 3.1.2 on 2022-06-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220628_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicios',
            name='asignar',
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='asignar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.quequieres'),
            preserve_default=False,
        ),
    ]
