# Generated by Django 3.1.2 on 2022-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220628_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicios',
            name='Duracion',
            field=models.IntegerField(),
        ),
    ]
